### PR TITLE
Update to 1.6.4

### PR DESCRIPTION
**Pull request by linuxhw**
@tpgxyz 

Please look.

BTW, can I upload sources to https://file-store.openmandriva.org/ by myself?

### CODE REVIEW

**Comment by AngryPenguinPL** [comment]
Hi, @linuxhw, if you want upload files and compile package for OpenMandriva you need create account on https://abf.openmandriva.org and In addition account must be verified by one of the admins (due to bots). It is best to enter the channel on matrix https://app.element.io/#/room/#openmandriva-space:matrix.org in room openmandriva-cooker or irc liberachat openmandriva-cooker after creating an account and ask for manual verification.

**Review by tpgxyz — COMMENTED** [review]
LGTM

**Comment by tpgxyz** [comment]
@linuxhw  Hello, sure you can upload stuff by yourself, as @AngryPenguinPL  described it well, first you have to create account on https://abf.openmandriva.org/ Rest is a piece of cake :)

**Comment by AngryPenguinPL** [comment]
already commited by @berolinux https://github.com/OpenMandrivaAssociation/hw-probe/commit/35956026a8ed673252bb3deb42b8971a4588ed2f

**Pull request closed without merging**
